version: '2.4'
services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - devDojo_maratona_data:/var/lib/mysql
volumes:
  devDojo_maratona_data: